# Generated by Django 4.1.5 on 2023-01-21 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_post_image_likepot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikePot',
            new_name='LikePost',
        ),
    ]
